using System.ComponentModel.DataAnnotations;


namespace HomecareApp.Models;

public class Appointment
{
    // Auto-generated by database - no validation needed
    public int AppointmentId { get; set; }
<<<<<<< Updated upstream
=======
    
    // Required form fields - non-nullable with [Required]
    [Required(ErrorMessage = "Client is required")]
>>>>>>> Stashed changes
    public int ClientId { get; set; }
    public int AvailableDayId { get; set; }
<<<<<<< Updated upstream
    public TimeSpan StartTime { get; set; }
    public TimeSpan EndTime { get; set; }
    [Required(ErrorMessage = "Task description is required")]
    [StringLength(500, MinimumLength = 5, ErrorMessage = "Task description must be between 5 and 500 characters")]
    public string? TaskDescription { get; set; }

    [Required(ErrorMessage = "Client is required")]
=======

    // If you want times to be auto-populated from AvailableDay, remove [Required]
    // If you want users to input times manually, keep [Required]
    [DataType(DataType.Time)]
    public TimeSpan StartTime { get; set; }

    [DataType(DataType.Time)]
    public TimeSpan EndTime { get; set; }
    
    // Required field - non-nullable string with validation
    [Required(ErrorMessage = "Task description is required")]
    [StringLength(500, MinimumLength = 5, ErrorMessage = "Task description must be between 5 and 500 characters")]
    public string TaskDescription { get; set; } = string.Empty;
>>>>>>> Stashed changes
    public User? Client { get; set; }

    [Required(ErrorMessage = "Available day is required")]
    public AvailableDay? AvailableDay { get; set; }
}

// Fiks warnings??